env = "local"

[http_server]
address = "localhost:8082"
timeout = "3s"
idle_timeout = "6s"
user = "user"
password = "password123"

[db_conn]
user = "postgres"
password = "postgres"
host = "localhost"
port = 5432
name = "url_shortener"

[alias]
length = 8
life_length = "720h"

