// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AliasGenerator is an autogenerated mock type for the AliasGenerator type
type AliasGenerator struct {
	mock.Mock
}

// Generate provides a mock function with given fields:
func (_m *AliasGenerator) Generate() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewAliasGenerator creates a new instance of AliasGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAliasGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *AliasGenerator {
	mock := &AliasGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
