// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	domain "github.com/MaKYaro/url-shortener/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// URLGetter is an autogenerated mock type for the URLGetter type
type URLGetter struct {
	mock.Mock
}

// GetURL provides a mock function with given fields: alias
func (_m *URLGetter) GetURL(alias string) (*domain.Alias, error) {
	ret := _m.Called(alias)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 *domain.Alias
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Alias, error)); ok {
		return rf(alias)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Alias); ok {
		r0 = rf(alias)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Alias)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(alias)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewURLGetter creates a new instance of URLGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLGetter {
	mock := &URLGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
